config/routes.rb
Rails.application.routes.draw do
  get 'users/dashboard'

  devise_for :admins
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"} 
  # devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks" }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # devise_for :users, :controllers => { registrations: 'registrations' }

  resources :users
  resources :contests do
    get :archive,  on: :member
    get :archived, on: :collection
    
  	resources :cells, except: [:index]
  end
    
  
  get '/users/:id/dashboard', to: 'users#dashboard', as: 'dashboard'
  get '/search', to: 'contests#_search', as: 'search'
  get '/contests/:id/box_score', to: 'contests#box_score', as: 'box_score'
  get '/contests/:id/display_owners', to: 'contests#display_owners'
  get '/pages/landing', to: 'pages#landing', as: 'landing'

  get '/home', to: 'layouts#home'
  get '/prizes', to: 'layouts#prizes'
  get '/how-to', to: 'layouts#howto'
  get '/contact', to: 'layouts#contact'
  get '/contests/:id/my_squares', to: 'contests#my_squares'

  root to: 'layouts#home'
end

app/models/contest.rb
class Contest < ActiveRecord::Base
  include Archivable::Model
  has_many :cells
  has_many :users

  before_create :shuffler, :populate_range
  before_save :capitalize_teams
  # accepts_nested_attributes_for :box_score
  serialize :box_score


  def shuffler
    self.home_axis = self.home_axis.shuffle
    self.away_axis = self.away_axis.shuffle
  end

  

  def populate_range
  	self.available_nums = (0..99).to_a
  end

def event_name
    self.home_team + " at " + self.away_team
  end

  def close_time
    (self.event_date.to_time - 15.minutes).to_datetime.utc.strftime("%l:%M %p")
  end

  def self.search(search)
    search.capitalize!
    where("home_team LIKE ? OR away_team LIKE ?", "%#{search}%", "%#{search}%")
  end

  def capitalize_teams
    self.home_team = self.home_team.split.collect(&:capitalize).join(' ') if self.home_team && !self.home_team.blank?
    self.away_team = self.away_team.split.collect(&:capitalize).join(' ') if self.away_team && !self.away_team.blank?
  end

  
  
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  # before_filter :authenticate_user!, :except => [:show...]

  respond_to :html, :xml, :json

   include Archivable::Controller


  def index

    if params[:search]
      @contests = Contest.search(params[:search]).order("created_at DESC")
    else
  	 @contests = Contest.where(archived:false)
    end
  end

  def search 
    
  end

  def new
  	@contest = Contest.new
  end

  def show
    redirect_to new_user_session_path unless logged_in? 
    @contest = Contest.find(params[:id])
    # begin
    if closed?(@contest)
      @nums = []
        if request.xhr?
          # p "AJAX"
          @contest.available_nums.each{|num| @nums << num.to_i}
          render :json => @nums
        else
          # flash[:notice] = "NO AJAX"
          # p "NO AJAX"
          # redirect_to login_path
        end
    end
    # rescue 
      # flash[:notice] = "ERROR SUCKAA"
    # render '_board'
    # end
  end

  def create
    @contest = Contest.new(contest_params)
    p contest_params
  	if @contest.save
      flash[:notice] = "Your Board has been created"
      redirect_to contest_path(@contest)
    else
      flash[:error] = "Errrror"
      @errors = @contest.errors.full_messages	
    end
  end

  def edit
  	@contest = Contest.find(params[:id])

  end


  def update
  	@contest = Contest.find(params[:id])
   
    @contest.save
    if @contest.persisted?
    @contest.update_attributes(contest_params)
  		flash[:notice] = "Your changes have been saved"
  		render 'show'
  	else
  		@errors = @contest.errors.full_messages	
  		render 'edit'
  	end
  end


  def destroy
  	@contest = Contest.find(params[:id])
  	@contest.destroy
  	flash[:notice] = "Your Board has been deleted"
  	redirect_to archived_contests_path
  end

  def box_score
    @contest = Contest.find(params[:id])
    render '_box_score'

  end

  def display_owners
    @contest = Contest.find(params[:id])
    if closed?(@contest)
      render json: @contest.cells
    end
  end

  def archive
    @contest = Contest.find(params[:id])
    @contest.archive!
    flash[:notice] = "Archived!!!"
    redirect_to contests_path

  end

  def archived
    @contests = Contest.where(archived:true)
    @archive_msg = "Archived Contests"
    render 'index'
  end

   def my_squares
    p params
    @my_squares = Cell.where(contest_id: params[:id], user_id: current_user.id)
    # byebug
    render json: [@my_squares, current_user.name]
  end




  private
  def contest_params
    params.require(:contest).permit(:event_name, :event_date, :cell_value, :sport, :reserve, :prizes, :home_team, :away_team, :archived, :box_score => [:home => [:first, :half, :third, :final], :away => [:first, :half, :third, :final]])
  end

end

app/helpers/contests_helper.rb
module ContestsHelper

  $quarters = ["first", "half", "third", "final"]

  def home_axis_populater(board)
    i = 0
    home_axis_string = ""
    10.times do
      home_axis_string += "<div class='col s1 home_num'>"
      if closed?(board)
        home_axis_string += board.home_axis[i] + "</div>"
      else
        home_axis_string += "🏈" + "</div>"
      end
      i += 1
      home_axis_string
    end
    home_axis_string
  end

  def away_axis_populater(board, x)
    axis_val = board.away_axis[x]
    html_string = "<div class='row #{x}'>
  <div class='s1 away_num'>"
    if closed?(board)
      html_string += axis_val
    else
      html_string +=  "🏈"
    end

    return html_string+ "</div>"
  end

  def row_checkbox_populater(row, board)
    z = 0
    string = ""
    10.times do
      string += "<div class='col s1 "
        if closed?(board)
          string += "closed_cells"
        else
          string+= "square"
        end
      string +="'> 
    <label for='#{row}#{z}' value='#{row}#{z}'>
    <input type='checkbox' id='#{row}#{z}' name='cell[position][]' value='#{row}#{z}'>
    <end>
    </label>
    </div>"
      z += 1
    end
    return string + "</div>"
  end

  def format_num(number)
    if number[0] == "0"
      number = number[1]
    end
    number
  end

  def remove_selected_nums(board, array)
    array.each{|number| board.available_nums.delete(format_num(number))}
    board.available_nums
  end

  def closed?(board)

    (board.event_date.to_time - 15.minutes).to_datetime <= DateTime.now || board.available_nums.length == 0
  end



  def display_event_date_or_message(board)
    if closed?(board)
      return "Sorry. Squares Are Closed."
    else
      if board.available_nums.length == 0
        return "Sorry. All Cells Are Taken"
      end
    end
    # board.event_date.strftime("%b %e, %l:%M %p" )
    board.event_date.strftime("%b %e, %l:%M %p")
  end



  def assign_closed_positions(board, cell)
        column = cell.position[0][1]
        row = cell.position[0][0]

        row = row.to_i
        column = column.to_i

        @cell = cell.update_attributes(positionx: board.home_axis[column], positiony: board.away_axis[row] )
        p @cell
        cell.save
      board.save
  end



  def find_winner(board, quarter)
    @winner_data = []
    column = board.box_score["home"][quarter][-1]
    row = board.box_score["away"][quarter][-1]
    p "LOGIC ROW"
    p row
    p "LOGIC COLUMN"
    p column
    @cell = Cell.where(contest_id: board.id, positionx: column.to_i, positiony: row.to_i)
    p @cell
    @user = User.find(@cell[0].user_id)
    @winner_data = [@user, @cell]

  end


  def quarter_over?(board, quarter)
    return false if board.box_score == nil 
    board.box_score["home"][quarter] != "" && board.box_score["away"][quarter] != ""
  end

  def insert_value_for_form(board, quarter, team)
    return "" if board.box_score == nil
    if board.box_score[team][quarter] == ""
      return ""
    else
      return board.box_score[team][quarter]
    end
  end

  def  sep_cells_on_close(board)

     
  

  end
end

app/views/contests/_archives.html.erb
<h2>Archived Boards</h2>

<ul>

	
  <% @contests.sort {|a,b| b.event_date <=> a.event_date}.each do |contest| %>
	<li>contest.</li>
</ul>

app/views/contests/_board.html.erb
    <h3 class='board_info event_name' id="contest_id" c-id=<%= @contest.id %>><%= @contest.home_team %> Vs <%= @contest.away_team %> </h3>

    <!-- Tabs -->
    <div class="row" id="grid">
    <div class="col s12">
      <ul class="tabs red valign-wrapper">
        <li class="tab col s3 red"><a href="#test1">Box Score</a></li>
        <li class="tab col s3 red"><a  href="#test2">Event Details</a></li>
        <li class="tab col s3 red"><a class="active" href="#test3" >See Grid</a></li>
        <li class="tab col s3 red"><a href="#test4">Winning</a></li>
      </ul>
    </div>
    <div id="test1" class="col s12">
      <% if closed?(@contest) %>
    <h2>Box Score:</h2>
    <ul>
      <li><%= render 'box_score' %></li>
        
    </ul>
    <% end %>
    <% $quarters.each do |quarter| %>
      <% if quarter_over?(@contest, quarter) %>
        <h2><%=  find_winner(@contest, quarter)[0].full_name  %> has the winning square for the  <%= quarter.capitalize %> - Cell <%= @winner_data[1][0].position[0].to_i + 1 %></h2>
      <% end %>
    <% end %>
  <% else %>
    <h3>Event is still live. Check back after final.</h3>
  </div>


    <div id="test2" class="col s12">
       <h4 class='board_info'><%= display_event_date_or_message(@contest) %></h4>
    <h4 class='board_info'>Squares will close 15 minutes prior to start of event at <%=@contest.close_time  %></h4> 
    <!-- <h4 class='board_info'>Event - <%#= @contest.event_date.utc  %></h4>  -->
    <% if current_user.admin? %>
      <ul>
      <li><%= link_to "Edit Event Details",  edit_contest_path(@contest), class: " claim-btn waves-red waves-effect edit-contest" %></li>
       <li> </li>
    </ul>
    <% end %>
    </div>
    <div id="test3" class="col s12"> <div id='num_pool'>
      <%= @contest.available_nums %>
    </div> 
    <!-- <button class="btn-large z-depth-4" id="display_board"> Show Taken </button> -->
    <h3 class="home-team-row team-header"><%= @contest.home_team.split(" ").pop %></h3>
  <div class="row home_row board">
    <!-- <div class="col s1 corner"></div> -->
      <%= raw home_axis_populater(@contest) %>
  </div>
  <h1 class="vertical-text team-header"><%= @contest.away_team.split(" ").pop %></h1>
<ul class="legend hide-on-med-and-down">
  <li><div class="color-box green"></div><span>Available</span></li>
  <li><div class="color-box black"></div><span>Taken</span></li>
</ul>
  <form action="/contests/<%= @contest.id %>/cells" method='POST' id="form" >
      <% i = 0 %>
    <% 10.times do%>
        <%= raw away_axis_populater(@contest, i ) %>
    <%= raw row_checkbox_populater(i, @contest) %>
      <%  i += 1 %>
    <% end %>
    <!-- <input type="hidden" name='cell[position][]' value="2"> -->
    <input type="hidden" name='cell[user_id]' value="<%= current_user.id %>">
    <input type="hidden" name='cell[contest_id]' value="<%= @contest.id %>">
    <div class="random_buttons">
      
    <button value="random2" class='claim-btn  waves-effect waves-red' id="random2">Random 2</button>
    <button value="random5" class='claim-btn waves-effect waves-red' id="random5">Random 5</button>
    </div>
    <div>
      <input type="submit" value="Claim Selected Squares" id='claim-selected' class='  swaves-effect waves-red'>
    </div>

  </form></div>
    <div id="test4" class="col s12">    <h4 class='board_info'><a href="#">Winning</a></h4>
</div>
  </div>
  <!--  -->


   
    

   
  <br>
  <br>
  <br> 

app/views/contests/_box_score.html.erb
  <table class"striped bordered">



    <!-- <thead><th>Winners:</th></thead> -->
    <thead>
      <tr>
        <th data-field="team">Team</th>
        <th data-field="1st">1st</th>
        <th data-field="half">Half</th>
        <th data-field="3rd">3rd</th>
        <th data-field="final">Final</th>
      </tr>
    </thead>
    <tbody>
      <tr>
       <td> <%= @contest.home_team %></td>
       <td><input name="contest[box_score[home[first]]]" type="text" class="box_score_item" value="<%= insert_value_for_form(@contest, "first", "home") %>"/></td>
       <td><input name="contest[box_score[home[half]]]" type="text" class="box_score_item" value="<%= insert_value_for_form(@contest, "half", "home") %>"/></td>
       <td><input name="contest[box_score[home[third]]]" type="text" class="box_score_item" value="<%= insert_value_for_form(@contest, "third", "home") %>"/></td>
       <td><input name="contest[box_score[home[final]]]" type="text" class="box_score_item" value="<%= insert_value_for_form(@contest, "final", "home") %>"/></td>
     </tr>
     <tr>
       <td> <%= @contest.away_team %></td>
       <td><input name="contest[box_score[away[first]]]" type="text"  class="box_score_item" value="<%= insert_value_for_form(@contest, "first", "away") %>"/></td>
       <td><input name="contest[box_score[away[half]]]" type="text" class="box_score_item" value="<%= insert_value_for_form(@contest, "half", "away") %>"/></td>
       <td><input name="contest[box_score[away[third]]]" type="text" class="box_score_item" value="<%= insert_value_for_form(@contest, "third", "away") %>"/></td>
       <td><input name="contest[box_score[away[final]]]" type="text" class="box_score_item" value="<%= insert_value_for_form(@contest, "final", "away") %>"/></td>

     </tr>
   </tbody>

 </table>

app/views/contests/_search.html.erb
   <%= form_tag(contests_path, :method => "get", id: "search") do %>
    <%= text_field_tag :search, params[:search], placeholder: "City or Team Name", class:'capitalize', id:'search-input' %>
    <%= submit_tag "Search", :name => nil , class:" search-submit" %>
    <%#= button_to "Reset", type="reset" %>
  <% end %>

app/views/contests/edit.html.erb
<%= form_for @contest do |f|%>
<div class='input-field home-away'>
  <%= f.label :home_team%>
  <%= f.text_field :home_team, placeholder: "Home Team", class: "home-team"%>
  <h4>at </h4>
  <%= f.label :away_team%>
  <%= f.text_field :away_team, placeholder: "Away Team", class:"away-team"%>
</div>

<div>
<input class="flatpickr" type="text" placeholder="Select Date.." name="contest[event_date]">
</div>
<div class="input-field inline  ">
  <%= f.label :reserve %>
  <%= f.text_field :reserve %>
</div>

<div class=" input-field inline ">
  
  <input name="contest[sport]" type="radio" id="Football" class="with-gap"/>
  <label for="Football" >Football</label>

  <input name="contest[sport]" type="radio" id="Basketball" class="with-gap"/>
  <label for="Basketball">Basketball</label>
</div>

<div class='range-field '>
  <%= f.label :cell_value%>
  <%= f.range_field :cell_value, min:'0', max:'50', step: '1'%>
</div>

<div> 
  <%= f.label :prizes %>
  <%= f.text_field :prizes, placeholder: "Separate by comma" %>
</div>


<% if closed?(@contest) %>
<%= render 'box_score'%>
<% end %>

<%= f.submit 'Update Board', class:'claim-btn waves-effect ' %>
<%= link_to "Delete Board", contest_path(@contest), method: "delete", class: "claim-btn waves-red waves-effect " %>
<% end %>

app/views/contests/index.html.erb
<!-- <div><p><iframe src="http://odds.zetamicro.com/xTicker.asp?bgColor=FFFFFF" width="800" height="180" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" class="" ></iframe></p></div> -->

<%#= render 'search', layout: false %>

<% if @contests.empty? %>
  <h3>No squares right now</h3>
<% else %>

  <h2 class='contest-list'>
    <% if @archive_msg %>
       Archived Boards
    <% else %>
      Contest List
    <% end %>

  </h2>
<% end %>
<div >
  <% @contests.sort {|a,b| b.event_date <=> a.event_date}.each do |contest| %>
    <div class ="contest-card wobble animated " contest_id="<%= contest.id %>">
      <div class="card col s3 teal lighten-3 ">
        <h4><%= link_to contest.event_name, contest_path(contest), class:"event_index "%></h4>
      	<div class="card-text">Starts: <%= contest.event_date.utc.strftime("%b %e, %l:%M %p")%></div>
  			<div class="card-text"><%= contest.available_nums.length %> squares available</div>
      
        <% if logged_in? && current_user.admin? %> 
          <% if contest.archived? %>
            <div><h6><%= link_to 'Permanently Delete', contest_path(contest), method: "delete" %></h6></div>
          <% end %>
          <div><h6><%= link_to contest.archived? ? :Unarchive : :Archive, archive_contest_path(contest) %> </div>
        <% end %>

    </div>
  </div>
<% end %>

      <!-- <div class="row">
      <div class="col s12 m5">
        <div class="card-panel teal">
          <span class="white-text">I am a very simple card. I am good at containing small bits of information.
          I am convenient because I require little markup to use effectively. I am similar to what is called a panel in other frameworks.
          </span>
        </div>
      </div>
    </div> -->


<%#= link_to 'See Archived Users', archived_users_path %></h6></li>

app/views/contests/new.html.erb
<%= form_for @contest do |f|%>
<div class='input-field home-away'>
  <%= f.label :home_team%>
  <%= f.text_field :away_team, placeholder: "Away Team", class:"away-team capitalize"%>
  <h4>At</h4>
  <%= f.label :away_team%>
  <%= f.text_field :home_team, placeholder: "Home Team", class: "home-team capitalize"%>
</div>

<div>
  <%= f.datetime_local_field :event_date, class: "flatpickr" %>
<!-- <input class="flatpickr" type="text" placeholder="Select Date.." name="contest[event_date]"> -->
</div>
<div class="input-field inline  ">
  <%= f.label :reserve %>
  <%= f.text_field :reserve %>
</div>

<div class=" input-field inline ">
  <input name="contest[sport]" type="radio" id="football" class="with-gap" value="football"/>
  <label for="football" >Football</label>

  <input name="contest[sport]" type="radio" id="basketball" class="with-gap" value="basketball"/>
  <label for="basketball">Basketball</label>
</div>

<div class='range-field '>
  <%= f.label :cell_value%>
  <%= f.range_field :cell_value, min:'0', max:'50', step: '1'%>
</div>

<div> 
  <%= f.label :prizes %>
  <%= f.text_field :prizes, placeholder: "Separate by comma" %>
</div>

  <% if @contest.event_date && closed?(@contest) %>
 <div>
  <table class"striped bordered">

    <!-- <thead><th>Winners:</th></thead> -->
     <thead>
          <tr>
              <th data-field="team">Team</th>
              <th data-field="1st">1st</th>
              <th data-field="half">Half</th>
              <th data-field="3rd">3rd</th>
              <th data-field="final">Final</th>
          </tr>
      </thead>
        <tbody>
            <tr>
               <td><%= @contest.home_team %></td>
               <td><input type="text"></td>
               <td><input type="text"></td>
               <td><input type="text"></td>
               <td><input type="text"></td>
            </tr>
            <tr>
               <td><%= @contest.away_team %></td>
              <td><input type="text"></td>
               <td><input type="text"></td>
               <td><input type="text"></td>
               <td><input type="text"></td>

            </tr>
        </tbody>
  
    </table>

</div>
<% end %>

<%= f.submit 'Create Board', class:'btn waves-effect' %>
<% end %>

app/views/contests/show.html.erb
<div class='board_display'><%= render 'board', layout: false %></div>