config/routes.rb
Rails.application.routes.draw do
  get 'users/dashboard'

  devise_for :admins
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"} 
  # devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks" }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # devise_for :users, :controllers => { registrations: 'registrations' }

  resources :users
  resources :contests do
    get :archive,  on: :member
    get :archived, on: :collection
    
  	resources :cells, except: [:index]
  end
    
  
  get '/users/:id/dashboard', to: 'users#dashboard', as: 'dashboard'
  get '/search', to: 'contests#_search', as: 'search'
  get '/contests/:id/box_score', to: 'contests#box_score', as: 'box_score'
  get '/contests/:id/display_owners', to: 'contests#display_owners'
  get '/pages/landing', to: 'pages#landing', as: 'landing'

  get '/home', to: 'layouts#home'
  get '/prizes', to: 'layouts#prizes'
  get '/how-to', to: 'layouts#howto'
  get '/contact', to: 'layouts#contact'
  get '/contests/:id/my_squares', to: 'contests#my_squares'

  root to: 'layouts#home'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :cells


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:google_oauth2, :facebook]

  # def self.from_omniauth(auth)
  #   where(auth.slice(provider: auth.provider, uid: auth.uid)).first_or_create do |user| 
  #     user.provider = auth.provider
  #     user.uid = auth.uid
  #     user.email = auth.info.email 
  #     user.avatar = auth.info.picture
      
  #   end
  # end

  def self.from_omniauth(access_token)
  data = access_token.info
  user = User.where(:email => data["email"]).first
  unless user
    # byebug
    password = Devise.friendly_token[0,20]
    user = User.create(name: data["name"], email: data["email"],
      password: password, password_confirmation: password, avatar: data['image'])
  end
  user
end

 

  def self.new_with_session(params, session)
    if session['devise.user_attributes']
      new(session['devise.user_attributes'], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def self.first_name
    name.split(" ")[0..-2]
  end

  def self.last_name
    name.split(" ")[-1]
  end
  

  

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  	
  	if request.xhr?
  		@response  = ids_in_initials_out(@users)
  		render json: @response
  	else
  		render 'index'
  	end
  end

  def show
    @user = User.find(params[:id])
    if request.xhr?
      @initials = id_in_initial_out(@user.id)
      render json: @initials
    end
  end

  def dashboard
  end
  
end

app/helpers/users_helper.rb
module UsersHelper

# 	def admin?
# 		current_user.admin? 
# 	end

# 	# def current_user
# 	# 	@cached_user = @cached_user || User.find_by(id: session[:user_id])
# 	# end

	def logged_in?
    	current_user != nil
  	end

	def recent
		Cell.where(user_id: current_user.id).order(created_at: :desc).limit(5)
		
	end

	def ids_in_initials_out(users)
		user_initials = {}
		users.each do |user|
			user_initials[user.id] = user.first_name[0] + user.last_name[0]
		end
		user_initials	
	end

	def id_in_initial_out(user_id)
		@user = User.find(user_id)
		@user.first_name[0] + @user.last_name[0]
	end
end

app/views/users/dashboard.html.erb
<h1>User Dashboard</h1>

<h4><%= link_to "Edit Profile", edit_user_registration_path, class: "waves-effect waves-light btn-large"%></h4>



	<h3>Last 5 Squares</h3>
	<% if recent != []  %>

	<ul>
	<% recent.each do |cell| %>
		<h4>
			
		<li><%= link_to Contest.find(cell.contest_id).event_name, contest_path(cell.contest_id) %>
			<ul class="browser-default" ><li recent_item>Cell Position - <%= cell.position[0] %></li></ul>
		</li>
		</h4>
	<% end %>
	<% else %>
		<h4><li>You have no recent squares.</li></h4>
		<h4><li><%= link_to 'Pick Some Squares Now', contests_path %></li></h4>
		<% end %>
	</ul>

		

app/views/users/index.html.erb
<% @users.each do |user| %>
	<ul>
		<li><h3><%= link_to user.email, user_path(user) %></h3>
				<% user.cells.each do |cell| %>
			<ul>
					<li><%= link_to cell, contest_path(cell.contest_id) %></li>
			</ul>
				<% end %>
		</li>
	</ul>
	
<% end %> 