config/routes.rb
Rails.application.routes.draw do
  get 'users/dashboard'

  devise_for :admins
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"} 
  # devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks" }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # devise_for :users, :controllers => { registrations: 'registrations' }

  resources :users
  resources :contests do
    get :archive,  on: :member
    get :archived, on: :collection
    
  	resources :cells, except: [:index]
  end
    
  
  get '/users/:id/dashboard', to: 'users#dashboard', as: 'dashboard'
  get '/search', to: 'contests#_search', as: 'search'
  get '/contests/:id/box_score', to: 'contests#box_score', as: 'box_score'
  get '/contests/:id/display_owners', to: 'contests#display_owners'
  get '/pages/landing', to: 'pages#landing', as: 'landing'

  get '/home', to: 'layouts#home'
  get '/prizes', to: 'layouts#prizes'
  get '/how-to', to: 'layouts#howto'
  get '/contact', to: 'layouts#contact'
  get '/contests/:id/my_squares', to: 'contests#my_squares'

  root to: 'layouts#home'
end

app/controllers/layouts_controller.rb
class LayoutsController < ApplicationController
  def home
  end
end

app/views/layouts/application.html.erb
  <!DOCTYPE html>
  <html lang="en">
  <head>
    <title>SquaringIsCaring</title>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="//cdn.jsdelivr.net/jquery.color-animation/1/mainfile"></script>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= csrf_meta_tags %>
    
    <!-- Compiled and minified JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>
    <!-- Compiled and minified CSS -->

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">
    <!-- Font Awesome -->
    <script src="https://use.fontawesome.com/13ab5ba0ee.js"></script>
    <!-- flatpicker -->
    <script type="text/javascript" src="https://unpkg.com/flatpickr"></script>
    <script src="https://use.fontawesome.com/e962ccf885.js"></script>
    <script src="https://use.fontawesome.com/e962ccf885.js"></script>

    <link rel="stylesheet" href="https://unpkg.com/flatpickr/dist/flatpickr.min.css">
  <!-- Animate.css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    
  </head>

  <body>
    <nav>

      <meta name="viewport" content="width=device-width" />

      <div class="nav-wrapper">
        <a href="/home" class="brand-logo title-bar">Squares</a>
        <span><%= render 'contests/search', layout: false %></span>
        <ul class="right ">
          <% if user_signed_in? %>
            <li ><%= link_to current_user.name, edit_user_registration_path %></li>
            <li ><%= link_to 'Dashboard', dashboard_path(current_user), id: "dashboard" %></li>
          <% else %>
            <li>        <%= link_to 'Login', new_user_session_path%>
</li>
            <!-- <li><%#= link_to 'Login with Google', user_google_oauth2_omniauth_authorize_path%></li> -->
            <li><%= link_to 'Register', new_user_registration_path %></li>
          <% end %>
          <li><%= link_to 'How To', how_to_path %></li>
          <!-- Dropdown Trigger -->
          <li><a class="dropdown-button"  data-activates="dropdown1" class=" nav-button" ><i class="large material-icons ">view_list</i></a></li>
        </ul>
      </div>
    </nav>
    <ul id="dropdown1" class="dropdown-content">
          <% if user_signed_in? %>
            <% if current_user.admin? %>
              <li><%= link_to 'Create a Board', new_contest_path %></li>
              <li><%= link_to "The Archives", archived_contests_path %></li>
            <% end %>
            <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
          <% end %>
      <!-- <li><%#= link_to 'Balance', edit_user_registration_path%></li> -->
      
    </ul>

    <div class='container'>

      <div>
        <% if flash[:error] -%>
       <h2><p class='error red'><%=h flash[:error] %></p></h2>
        <% end -%>
        <% if flash[:notice] -%>

          <h2 ><p class='notice '><%=h flash[:notice] %></p></h2>
        <% end -%>
       

      </div>
      <%= yield %>
    </div>
    <div class='footer'>
      <li><%= link_to 'Contact Us', contact_path, class: 'contact'%></li>
    <!-- </div> -->
      <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  </body>
  </html>

app/views/layouts/contact.html.erb
contact.html.erb

app/views/layouts/home.html.erb
<div class='home'>
  <a href='/prizes'><div class="cube animated bounceInRight" id="red">
    <div class="face">PRIZES</div>
    <div class="face"><div class=gift><i class="fa fa-gift" aria-hidden="true"></i></div></div>
  </div></a>

  <a href='/contests'><div class="cube animated bounceInDown" id="blue">
    <div class="face">UPCOMING SQUARES</div>
    <div class="face"><div class='cal'><i class="fa fa-calendar" aria-hidden="true"></i></div></div>
  </div></a>

  <a href='/search'><div class="cube animated bounceInLeft " id="green">
    <div class="face ">SEARCH</div>
    <div class="face "><div class='search '><i class="fa fa-search" aria-hidden="true"></i></div></div>
  </div></a>
  
  <a href='/contests'><div class="cube animated bounceInUp" id="yellow">
    <div class="face">TODAY'S GAMES</div>
    <div class="face"><div class='sq'><i class="fa fa-gamepad" aria-hidden="true"></i></div></div>
  </div>

</div></a>

app/views/layouts/howto.html.erb
<div class='how-to-container'>
  <h2 class='how-to-header'>How To</h2>
  <p>
    For every game, there is a 10 x 10 grid divided into 100 squares. Each user can select one or more squares. Once all the squares have been selected, we will randomly pick numbers from 0-9 for each team and assign a number to a particular row or column. The numbers assigned represent the last number in the score of each team: if the score of a game is Home 21 - Away 14, then the winning square is at the intersection of Home number 1 and Away number 4. No one knows what numbers each square will represent, so good luck and enjoy!
  <p>
</div>

app/views/layouts/prizes.html.erb
<h3 class='container'>Welcome to the Squares Prizes Page</h3>
	<h4 class='container'>Coming Soon</h4>